### PR TITLE
Feature/tematic switchers

### PR DESCRIPTION
**Pull request by kandebonfim**
This PR changes switchers text from "yes" and "no" to it's specific meaning:

**before**
before

**after**
after

Better now, @vhaidamus and @rafaelftp?

### CODE REVIEW

**Comment by kandebonfim** [comment]
This PR solves issue https://github.com/kandebonfim/keep-talking-and-nobody-explodes/issues/3.

**Comment by vhaidamus** [comment]
It is much better!! But I would stil make one change:

• Change the second question to "The last digit of the serial number is: "

**Comment by kandebonfim** [comment]
Ok, I changed some questions, @vhaidamus:
captura de tela 2016-01-27 as 13 17 48
https://github.com/kandebonfim/keep-talking-and-nobody-explodes/commit/a23e95f1382e8b5aa81c8754b2ed7ee7c8f5d993

**Comment by vhaidamus** [comment]
@kandebonfim merge merge merge ((:

**Pull request merged**
